[[pool]]
text = "绝望之为虚妄，正与希望相同。"
source = "鲁迅《希望》引用 Petöfi Sándor 的信"

[[pool]]
text = "物之反常者为妖。"
source = "纪晓岚《阅微草堂笔记》"

[[pool]]
text = "All models are wrong, but some are useful."
source = "George E. P. Box"

[[pool]]
text = "Do not go gentle into that good night."
source = "Dylan Thomas"

[[pool]]
text = "To the time to life, rather than to life in time."
source = "Blaise Pascal"

[[pool]]
text = "每个人都是依据他在世界上的使命拟定自己的计划。他想精熟某些技艺，想藉此得到某些荣耀和平安，想要在脚踏实地的人生里得到长久的幸福，无数的欢乐与愿景，构成了神奇的灯笼上面缤纷的图饰，在他的想象里展开；结束这场光影游戏的死亡，在黑暗的远方招手，但是欢乐的世界的光线遮蔽且扭曲了它。我们活在自己的梦境里，真实的命运却为我们铺了一条完全不同的道路。冥冥中的安排与我们自己的想象完全不一样，我们每踏出充满希望的脚步，紧跟而来的便是失望…直到看似遥远的死亡，突然结束这一场游戏。"
source = "康德 信"

[[pool]]
text = "朝闻道，夕死可矣。"
source = "《论语·里仁第四》"

[[pool]]
text = "有风自南，翼彼新苗。"
source = "陶渊明《时运》"

[[pool]]
text = "夜光之珠，不必出于孟津之河；盈握之璧，不必采于昆仑之山。"
source = "刘义庆《世说新语》"

[[pool]]
text = "黑夜给了我黑色的眼睛，\n我却用它寻找光明。"
source = "顾城《一代人》"

[[pool]]
text = "走过的人说树枝低了\n走过的人说树枝在长"
source = "顾城《墓床》"

[[pool]]
text = "The eternal mystery of the universe is its comprehensibility."
source = "Albert Einstein"

[[pool]]
text = "面对愚昧，神们自己也缄口不言。"
source = "席勒《奥尔良的姑娘》"

[[pool]]
text = "有我之境，以我观物，故物皆著我之色彩。"
source = "王国维《人间词话》"

[[pool]]
text = "一个时代结束的标志就是它开始被浪漫化。"
source = "兰德尔·柯林斯《发现社会》"

[[pool]]
text = "让一让，母牛们，生命短暂啊！"
source = "《百年孤独》"

[[pool]]
text = "任何公共领域的内容都日渐以娱乐的方式出现，人类悄无声息地成为娱乐的附庸，其结果是我们成了一个娱乐至死的物种。"
source = "《娱乐至死》"

[[pool]]
text = "你们可以改了，从真心改起！要晓得将来容不得吃人的人，活在世上。"
source = "《狂人日记》"

[[pool]]
text = "Seven times have I despised my soul:<br>The first time when I saw her being meek that she might attain height.<br>The second time when I saw her limping before the crippled.<br>The third time when she was given to choose between the hard and the easy, and she chose the easy.<br>The fourth time when she committed a wrong, and comforted herself that others also commit wrong.<br>The fifth time when she forbore for weakness, and attributed her patience to strength.<br>The sixth time when she despised the ugliness of a face, and knew not that it was one of her own masks.<br>And the seventh time when she sang a song of praise, and deemed it a virtue."
source = "Kahlil Gibran <em>Sand and Foam</em>"

[[pool]]
text = "绿蚁新醅酒，红泥小火炉。"
source = "白居易《问刘十九》"

[[pool]]
text = "The philosophers have only interpreted the world in various ways - the point however is to change it."
source = "Karl Marx"

[[pool]]
text = "欲进余以千秋之业，岂料余之一事无成也哉！"
source = "张岱《自为墓志铭》"

[[pool]]
text = "苍山负雪，明烛天南。"
source = "姚鼐《登泰山记》"

[[pool]]
text = "路漫漫其修远兮，吾将上下而求索。"
source = "屈原《离骚》"

[[pool]]
text = "天行有常，不为尧存，不为桀亡。"
source = "《荀子》"

[[pool]]
text = "木犹如此，人何以堪。"
source = "《世说新语·言语》"

[[pool]]
text = "后生可畏，焉知来者之不如今也。"
source = "《论语·子罕第二十三》"

[[pool]]
text = "人能弘道，非道弘人。"
source = "《论语·卫灵公第十五》"

[[pool]]
text = "Wir müssen wissen. Wir werden wissen."
source = "David Hilbert"

[[pool]]
text = "Talk is cheap. Show me the code."
source = "Linus Torvalds"

[[pool]]
text = "夫以铜为镜，可以正衣冠；以史为镜，可以知兴替；以人为镜，可以明得失。"
source = "唐太宗（自《旧唐书·魏徵传》）"

[[pool]]
text = "The amazing thing is that every atom in your body came from a star that exploded. And, the atoms in your left hand probably came from a different star than your right hand. It really is the most poetic thing I know about physics: You are all stardust. You couldn’t be here if stars hadn't exploded, because the elements - the carbon, nitrogen, oxygen, iron, all the things that matter for evolution - weren't created at the beginning of time. They were created in the nuclear furnaces of stars, and the only way they could get into your body is if those stars were kind enough to explode. So, forget Jesus. The stars died so that you could be here today."
source = "Lawrence M. Krauss"

[[pool]]
text = "天地不仁，以万物为刍狗。"
source = "老子《道德经》"

[[pool]]
text = "I could be bounded in a nutshell and count myself a king of infinite space."
source = "William Shakespare <em>Hamlet</em>"

[[pool]]
text = "The obtaining of satisfaction by submersion in misery is an expression of the general principle of finding satisfaction by losing the self in something greater, by dissolving the individuality, by getting rid of the self with its doubts, conflicts, pains, limitations and isolation."
source = "Karen Horney <em>The Neurotic Personality of Our Time</em>"

[[pool]]
text = "Nun sage ich: der Mensch und überhaupt jedes vernünftige<br>Wesen existiert als Zweck an sich selbst, nicht bloß als Mittel zum<br>beliebigen Gebrauche für diesen oder jenen Willen, sondern muß<br>in allen seinen sowohl auf sich selbst, als auch auf andere vernünftige<br>Wesen gerichteten Handlungen jederzeit zugleich als Zweck betrachtet werden."
source = "Immanuel Kant <em>Kritik der praktischen Vernunft</em>"

[[pool]]
text = "十年饮冰，难凉热血。"
source = "梁启超《饮冰室文集》"

[[pool]]
text = "已过的世代，无人记念；将来的世代，后来的人也不记念。"
source = "传道书 1:11"

[[pool]]
text = "世界若恨你们，你们该知道，在你们以前，它已恨了我。"
source = "若望福音 15:18"

[[pool]]
text = "惟愿公平如大水滚滚，使公义如江河滔滔。"
source = "阿摩司书 5:24"

[[pool]]
text = "那美好的仗我已经打过了，当跑的路我已经跑尽了，所信的道我已经守住了。从此以后，有公义的冠冕为我存留，就是按着公义审判的主到了那日要赐给我的；不但赐给我，也赐给凡爱慕他显现的人。"
source = "提摩太后书 4:6-8"

[[pool]]
text = "凡所过往，皆为序章。"
source = "莎士比亚《暴风雨》"

[[pool]]
text = "此心光明，亦复何言？"
source = "王阳明"

[[pool]]
text = "Writing at its best is a lonely life. Organizations for writers palliate the writer's loneliness, but I doubt if they improve his writing. He grows in public stature as he sheds his loneliness and often his work deteriorates. For he does his work alone, and if he is a good enough writer, he must face eternity or the lack of it each day.<br>For a true writer, each book should be a new beginning where he tries again for something that is beyond attainment. He should always try for something that has never been done or that others have tried and failed. Then sometimes, with good luck, he will succeed.<br>How simple the writing of literature would be if it were only necessary to write in another way what has been well written. It is because we have had such great writers in the past that a writer is driven far out past where he can go, out to where no one can help him."
source = "Ernest Miller Hemingway"

[[pool]]
text = "吾不识青天高，黄地厚。唯见月寒日暖，来煎人寿。"
source = "李贺《苦昼短》"

[[pool]]
text = "我们的时代，是一个理性化、理知化，尤其是将世界之迷魅加以祛除的时代；我们这个时代的宿命，便是一切终极而最崇高的价值，已自公共领域隐没……"
source = "韦伯《学术作为一种志业》"

[[pool]]
text = "民不畏死，奈何以死惧之。"
source = "老子《道德经》"

[[pool]]
text = "为天地立心，为生民立命，为往圣继绝学，为万世开太平。"
source = "张载（本版本自《横渠学案》）"

[[pool]]
text = "I have a dream that one day every valley shall be exalted, and every hill and mountain shall be made low, the rough places will be made plain, and the crooked places will be made straight; ..."
source = "Martin Luther King"

[[pool]]
text = "自由固不是钱所能买到的，但能够为钱而卖掉。"
source = "鲁迅 演讲《娜拉走后怎样》"

[[pool]]
text = "人是悬挂在自己编织的意义之网上的动物。"
source = "克利福德·格尔茨《文化的解释》引 马克斯·韦伯"

[[pool]]
text = "古人之观于天地、山川、草木、虫鱼、鸟兽，往往有得，以其求思之深而无不在也。夫夷以近，则游者众；险以远，则至者少。而世之奇伟、瑰怪，非常之观，常在于险远，而人之所罕至焉，故非有志者不能至也。有志矣，不随以止也，然力不足者，亦不能至也。有志与力，而又不随以怠，至于幽暗昏惑而无物以相之，亦不能至也。然力足以至焉，于人为可讥，而在己为有悔；尽吾志也而不能至者，可以无悔矣，其孰能讥之乎？此余之所得也！"
source = "王安石《游褒禅山记》"

[[pool]]
text = "文章憎命达，魑魅喜人过。"
source = "杜甫《天末怀李白》"

[[pool]]
text = "且夫我尝闻少仲尼之闻而轻伯夷之义者。"
source = "《庄子·外篇·秋水》"

[[pool]]
text = "天地有大美而不言，四时有明法而不议，万物有成理而不说。"
source = "《庄子·外篇·知北游》"

[[pool]]
text = "宽恕不是一种只把宽容给予过去和今天的纯思想的立场，它是向前看的一种能动的态度，是对于希望成为的东西的理解和促进。人类文化的多样性在我们的后面、四周，也在我们的前面。"
source = "列维-斯特劳斯《结构人类学》"

[[pool]]
text = "雪似故人人似雪，虽可爱，有人嫌。"
source = "苏轼《江神子·黄昏犹是雨纤纤》"

[[pool]]
text = "庐山烟雨浙江潮，未至千般恨不消。到得还来别无事，庐山烟雨浙江潮。"
source = "苏轼（存疑）"

[[pool]]
text = "人是近期的发明，并且正接近其终点。"
source = "《词与物：人文科学考古学》"

[[pool]]
text = "昔年名利，役碎顽心。气财酒色深沈。方寸之间，荆棘仿佛成林。因遇风仙省悟，觉从前、罪业弥深。便改正，便改正改正。改正改正。游历天心地肺，结云朋霞友，月伴风邻。自在逍遥快乐，绝尽搜寻。假使贫人退道，得荣华、富贵人钦。我不肯，我不肯不肯，不肯不肯。"
source = "马钰《满庭芳》"

[[pool]]
text = "时人不识凌云木，直待凌云始道高。"
source = "杜荀鹤《小松》"

[[pool]]
text = "哲学是把握在思想中的它的时代。"
source = "黑格尔《法哲学原理》"

[[pool]]
text = "季子平安否？便归来，平生万事，那堪回首！行路悠悠谁慰藉，母老家贫子幼。记不起，从前杯酒。魑魅搏人应见惯，总输他，覆雨翻云手，冰与雪，周旋久。泪痕莫滴牛衣透，数天涯，依然骨肉，几家能够？比似红颜多命薄，更不如今还有。只绝塞，苦寒难受。廿载包胥承一诺，盼乌头马角终相救。置此札，君怀袖。<br>我亦飘零久！十年来，深恩负尽，死生师友。宿昔齐名非忝窃，只看杜陵消瘦，曾不减，夜郎僝僽，薄命长辞知已别，问人生到此凄凉否？千万恨，为君剖。兄生辛未吾丁丑，共此时，冰霜摧折，早衰蒲柳。诗赋从今须少作，留取心魂相守。但愿得，河清人寿！归日急翻行戍稿，把空名料理传身后。言不尽，观顿首。"
source = "顾贞观《金缕曲》"

[[pool]]
text = "试问禅关，参求无数，往往到头虚老。磨砖作镜，积雪为粮，迷了几多年少。毛吞大海，芥纳须弥，金色头陀微笑。悟时超、十地三乘，凝滞四生六道。<br>谁听得、绝相岩前，无阴树下，杜宇一声春晓。曹溪路险，鹫岭云深，此处故人音窅。千丈冰崖、五叶莲开，古殿帘垂香袅。免葛藤丛里，婆娑游子，梦魂颠倒。"
source = "冯尊师《苏武慢·试问禅关》"

[[pool]]
text = "望长安，前程渺渺鬓斑斑。南来北往随征雁，行路艰难。青泥小剑关，红叶湓江岸，白草连云栈。功名半纸，风雪千山。"
source = "张可久《殿前欢·客中》"
